package decibelrestjava.frames;

import decibelrestjava.Settings;
import edu.stanford.ejalbert.BrowserLauncher;
import java.awt.Color;
import java.awt.Cursor;
import java.awt.event.InputEvent;

/**
 * Dialog box for entering Decibel API address, Application ID and Key.
 */
@SuppressWarnings("serial")
public class Options extends javax.swing.JDialog {

    /**
     * Creates new form OptionsWindow.
     */
    public Options(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        Settings.readApplicationSettings();
        txtApiAddress.setText(Settings.ApiAddress);
        txtApplicationID.setText(Settings.ApplicationID);
        txtApplicationKey.setText(Settings.ApplicationKey);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        lblDescription = new javax.swing.JLabel();
        lblApiAddress = new javax.swing.JLabel();
        txtApplicationID = new javax.swing.JTextField();
        lblApplicationID = new javax.swing.JLabel();
        txtApiAddress = new javax.swing.JTextField();
        lblApplicationKey = new javax.swing.JLabel();
        txtApplicationKey = new javax.swing.JTextField();
        lnkSignUp = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Options");
        setResizable(false);

        jPanel1.setLayout(new java.awt.GridBagLayout());

        lblDescription.setText("<html>Please enter the address of the Decibel API you would like to use and <br>your application ID and Key.</html>");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 10, 0);
        jPanel1.add(lblDescription, gridBagConstraints);

        lblApiAddress.setText("API Address");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(lblApiAddress, gridBagConstraints);

        txtApplicationID.setPreferredSize(new java.awt.Dimension(220, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(txtApplicationID, gridBagConstraints);

        lblApplicationID.setText("Application ID");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(lblApplicationID, gridBagConstraints);

        txtApiAddress.setPreferredSize(new java.awt.Dimension(220, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(txtApiAddress, gridBagConstraints);

        lblApplicationKey.setText("Application Key");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 0, 0);
        jPanel1.add(lblApplicationKey, gridBagConstraints);

        txtApplicationKey.setPreferredSize(new java.awt.Dimension(220, 20));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 10, 0, 0);
        jPanel1.add(txtApplicationKey, gridBagConstraints);

        lnkSignUp.setText("Sign up for the Decibel API");
        lnkSignUp.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                lnkSignUpMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                lnkSignUpMouseExited(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                lnkSignUpMousePressed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(13, 5, 10, 0);
        jPanel1.add(lnkSignUp, gridBagConstraints);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnOK.setText("OK");
        btnOK.setPreferredSize(new java.awt.Dimension(73, 23));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel2.add(btnOK, gridBagConstraints);

        btnCancel.setText("Cancel");
        btnCancel.setPreferredSize(new java.awt.Dimension(73, 23));
        btnCancel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 20);
        jPanel2.add(btnCancel, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 412, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 174, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        setSize(new java.awt.Dimension(428, 253));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Occurs when the OK button is clicked.
     * @param evt Event arguments.
     */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        Settings.ApiAddress = txtApiAddress.getText();
        Settings.ApplicationID = txtApplicationID.getText();
        Settings.ApplicationKey = txtApplicationKey.getText();
        Settings.writeApplicationSettings();
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * Occurs when the Cancel button is clicked.
     * @param evt Event arguments.
     */
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnCancelActionPerformed

    /**
     * Invoked when the mouse enters a component.
     * @param evt Event arguments.
     */
    private void lnkSignUpMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnkSignUpMouseEntered
        lnkSignUp.setForeground(Color.red);
        lnkSignUp.setCursor(new Cursor(Cursor.HAND_CURSOR));
    }//GEN-LAST:event_lnkSignUpMouseEntered

    /**
     * Invoked when the mouse exits a component.
     * @param evt Event arguments.
     */
    private void lnkSignUpMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnkSignUpMouseExited
        lnkSignUp.setForeground(Color.BLACK);
        lnkSignUp.setCursor(new Cursor(Cursor.DEFAULT_CURSOR));
    }//GEN-LAST:event_lnkSignUpMouseExited

    /**
     * Invoked when a mouse button has been pressed on a component.
     * @param evt Event arguments.
     */
    private void lnkSignUpMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lnkSignUpMousePressed
        if(evt.getModifiers() == InputEvent.BUTTON1_MASK) 
        {     
            try {
                new BrowserLauncher().openURLinBrowser("https://developer.decibel.net/signup");
            } catch (Exception e) {
            }
        }
    }//GEN-LAST:event_lnkSignUpMousePressed

    /**
     * @param args the command line arguments.
     */
    public static void main(String args[]) {

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                Options dialog = new Options(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblApiAddress;
    private javax.swing.JLabel lblApplicationID;
    private javax.swing.JLabel lblApplicationKey;
    private javax.swing.JLabel lblDescription;
    private javax.swing.JLabel lnkSignUp;
    private javax.swing.JTextField txtApiAddress;
    private javax.swing.JTextField txtApplicationID;
    private javax.swing.JTextField txtApplicationKey;
    // End of variables declaration//GEN-END:variables
}
