package decibelrestjava.frames;

import decibelrestjava.tables.TrackParticipantsTableModel;
import javax.swing.JTable;
import javax.swing.ListSelectionModel;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import queryresultholder.Participation;
import queryresultholder.Performance;
import queryresultholder.Track;

/**
 * Reads a Decibel Track object and displays a list of track performance participations.
 */
@SuppressWarnings("serial")
public class TrackParticipants extends javax.swing.JDialog {

    /**
     * Creates new form TrackParticipants
     */
    public TrackParticipants(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        initResultsTable();
    }

    /**
     * Shows the track participants dialog.
     *
     * @param track The selected track.
     */
    public void showDialog(Track track) {

        // Initialise the results table
        DefaultTableModel model = (DefaultTableModel) tblTrackParticipants.getModel();
        model.getDataVector().removeAllElements();

        Performance performance = track.getPerformances().getPerformance().get(0);

        long count = 0;
        for (Participation participation : performance.getParticipations().getParticipation()) {
            Object[] row = new Object[3];
            row[0] = count + 1;
            row[1] = participation.getName().split(",")[0];
            row[2] = participation.getName().split(",")[1];
            model.addRow(row);
            count++;
        }
        tblTrackParticipants.setModel(model);
        
        if(tblTrackParticipants.getModel().getRowCount() > 0)
            tblTrackParticipants.setRowSelectionInterval(0, 0);
        
        tblTrackParticipants.requestFocus();    
        
       this.setVisible(true);
    }

    /**
     * Initializes the result table columns.
     */
    private void initResultsTable() {

        // Create the result table model
        tblTrackParticipants.setModel(new TrackParticipantsTableModel());

        // Set the default column widths
        setTableColumnWidth(0, 57);
        setTableColumnWidth(1, 321);
        setTableColumnWidth(2, 321);
        tblTrackParticipants.setAutoResizeMode(JTable.AUTO_RESIZE_OFF);

        // Allow only single a selection
        tblTrackParticipants.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
    }

    /**
     * Sets a result table column width.
     *
     * @param column The column.
     * @param width The width.
     */
    private void setTableColumnWidth(int column, int width) {
        TableColumn col = tblTrackParticipants.getColumnModel().getColumn(column);
        col.setPreferredWidth(width);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jScrollPane1 = new javax.swing.JScrollPane();
        tblTrackParticipants = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        btnOK = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Track Participants");
        setResizable(false);

        tblTrackParticipants.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tblTrackParticipants);

        jPanel2.setLayout(new java.awt.GridBagLayout());

        btnOK.setText("OK");
        btnOK.setPreferredSize(new java.awt.Dimension(73, 23));
        btnOK.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOKActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.anchor = java.awt.GridBagConstraints.EAST;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel2.add(btnOK, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 715, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        setSize(new java.awt.Dimension(731, 313));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Occurs when the OK button is clicked.
     * @param evt Event arguments.
     */
    private void btnOKActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOKActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnOKActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                TrackParticipants dialog = new TrackParticipants(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOK;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblTrackParticipants;
    // End of variables declaration//GEN-END:variables
}
